# Numpy

In [1]:
import numpy as np

In [3]:
a=["Sachin","Sagar"]
print(a)

['Sachin', 'Sagar']


In [4]:
a=np.array([20,30,40,50])
print(a)

[20 30 40 50]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.dtype)

int32


In [7]:
a1=np.array(["2",5,3,2,1])
print(a1)
print(a1.dtype)

['2' '5' '3' '2' '1']
<U11


In [8]:
a2=np.array([2.3,2,4,5])
print(a2)
print(a2.dtype)

[2.3 2.  4.  5. ]
float64


### Working with array dim

In [9]:
a=np.array([2,5,8,20])
print(a.ndim)

1


In [10]:
# 0 dim
a2=np.array(20)
print(a2.ndim)

0


In [11]:
a3=np.array([[20,15,11]])
print(a3.ndim)

2


In [12]:
a4=np.array([[20,15,13],[15,10,25]])

In [13]:
print(a4.ndim)

2


## 3D data

In [15]:
a5=np.array([[[2,3,4,5]],[[2,3,4,5]]])
print(a5.ndim)
print(a5.shape)

3
(2, 1, 4)


In [16]:
print(a5)

[[[2 3 4 5]]

 [[2 3 4 5]]]


In [17]:
a6=np.array([[[2,3,4,5],[2,3,4,5]],[[21,31,41,51],[12,13,14,15]]])
print(a6)

[[[ 2  3  4  5]
  [ 2  3  4  5]]

 [[21 31 41 51]
  [12 13 14 15]]]


In [18]:
print(a6.ndim)

3


In [19]:
print(a6.shape) #shape of data

(2, 2, 4)


In [21]:
a7=np.array([[2,4,5,6],[9,5,6,4],[9,9,9,9],[5,7,8,3],[0,1,0,1]])
print(a7)

[[2 4 5 6]
 [9 5 6 4]
 [9 9 9 9]
 [5 7 8 3]
 [0 1 0 1]]


In [30]:
print(a7.ndim)

2


In [31]:
print(a7.shape)

(5, 4)


## working with slicing

In [33]:
a7[2:4,:]

array([[9, 9, 9, 9],
       [5, 7, 8, 3]])

In [34]:
a7[2:4,:2]

array([[9, 9],
       [5, 7]])

In [35]:
a8=np.array([[[[2,5,5,8],[8,7,10,12],[0,0,0,0],[5,1,7,55]],[[0,0,0,0],[1,1,1,1],[2,2,2,2],[3,3,3,3]]]])

In [36]:
a8

array([[[[ 2,  5,  5,  8],
         [ 8,  7, 10, 12],
         [ 0,  0,  0,  0],
         [ 5,  1,  7, 55]],

        [[ 0,  0,  0,  0],
         [ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]]]])

In [37]:
print(a8.shape)

(1, 2, 4, 4)


In [38]:
a8[0,1,0,3]

0

In [39]:
a8[0,0,3,3]

55